name: generate-weekly-customer
on:
  schedule:
    - cron: '1 1 * * 0'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://linkshare-admin.vercel.app/api/generate-weekly-customer'
