name: generate-hourly-view
on:
  schedule:
    - cron: '1,30 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://linkshare-admin.vercel.app/api/generate-hourly-view'
